language: csharp
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start || true"
  - sleep 3 # give xvfb some time to start
script:
  - ./build.sh
os:
  - linux
  - osx
cache:
  directories:
    - packages
    - tools
