init:
  - git config --global core.autocrlf true

version: '{build}'
image: Visual Studio 2017
build_script:
  - ps: ./build

# Build cache
cache:
  - packages -> **\packages.config
  - tools -> tools\packages.config
